function AnalyseGFPpunctaSummary(punctaCsvs, outDir, opts)
% AnalyseGFPpunctaSummary
%
% Multi-experiment analysis and plotting pipeline for GFP puncta
% measurements generated by the Fiji mitochondrial puncta-analysis macro.
%
% -------------------------------------------------------------------------
% OVERVIEW
% -------------------------------------------------------------------------
% This function reads one or multiple Fiji-generated
% GFP_Puncta_Summary.csv files, harmonises old and new output schemas,
% assigns experiment identity, parses experimental metadata from filenames,
% tracks Fiji segmentation settings, filters unwanted stages and timepoints,
% and generates descriptive puncta summaries and publication-oriented plots.
%
% Individual cell/ROI measurements from multiple experiments are pooled into
% one cleaned analysis table while retaining the source experiment and CSV
% file associated with every row.
%
% The function analyses the following puncta metrics:
%
%       Number of puncta per cell
%       Total puncta area
%       Mean puncta area
%       Largest punctum area
%       Mean puncta intensity
%       Total puncta integrated density
%       Fraction of GFP signal in puncta
%       Fraction of cell area occupied by puncta
%
% Fiji segmentation settings are tracked through RunLabel so datasets
% generated using different Threshold_SD and/or Min_Puncta_Size values can
% be identified and, by default, plotted separately.
%
% This function performs descriptive data summarisation and visualisation.
% It does NOT currently perform inferential statistical hypothesis testing.
%
% -------------------------------------------------------------------------
% INPUT
% -------------------------------------------------------------------------
% punctaCsvs : string, string array, or compatible list of file paths
%     One or more Fiji-generated GFP_Puncta_Summary.csv files.
%
%     Each supplied CSV is treated as one experiment unless custom
%     experiment labels are provided through opts.experimentLabels.
%
% outDir : character vector or string-compatible path
%     Output directory for cleaned tables, run-setting information,
%     descriptive summaries, plots, and FIG files.
%
%     If omitted or empty, the default output directory is:
%
%         <folder of first puncta CSV>\MATLAB_Analysis_Pooled
%
% opts : structure containing metadata, filtering, run-tracking, ordering,
%     and plotting options.
%
% -------------------------------------------------------------------------
% SUPPORTED FIJI INPUT FORMATS
% -------------------------------------------------------------------------
%
% 1) OLDER FIJI PUNCTA OUTPUT
%
%    Expected structure includes columns such as:
%
%         File
%         Stage
%         Cell_Area
%         Cell_Mean_GFP
%         Cell_IntDen_GFP
%         Cell_SD_GFP
%         Threshold
%         NPuncta
%         Total_Puncta_Area
%         Mean_Puncta_Area
%         Largest_Punctum_Area
%         Mean_Puncta_Intensity
%         Total_Puncta_IntDen
%         Puncta_Fraction
%         Area_Fraction
%
%    IMPORTANT:
%    The old "Threshold" column represents the measured threshold value
%    calculated for each individual cell/ROI.
%
%    It is NOT interpreted as the user-defined threshold SD multiplier.
%
%    During schema harmonisation:
%
%         Threshold -> Threshold_Value
%
%    The old-format table does not intrinsically record:
%
%         Threshold_SD
%         Min_Puncta_Size
%
%    These settings can optionally be supplied manually through:
%
%         opts.thresholdSDUsed
%         opts.minPunctaSizeUsed
%
% 2) NEWER FIJI PUNCTA OUTPUT
%
%    Expected structure includes:
%
%         File
%         Stage
%         Cell_Area
%         Cell_Mean_GFP
%         Cell_IntDen_GFP
%         Cell_SD_GFP
%         Threshold_SD
%         Threshold_Value
%         Min_Puncta_Size
%         NPuncta
%         Total_Puncta_Area
%         Mean_Puncta_Area
%         Largest_Punctum_Area
%         Mean_Puncta_Intensity
%         Total_Puncta_IntDen
%         Puncta_Fraction
%         Area_Fraction
%
%    Threshold_SD and Min_Puncta_Size record user-defined Fiji segmentation
%    settings and are used to identify segmentation runs.
%
%    Threshold_Value is a measured per-cell threshold and is NOT used to
%    distinguish segmentation runs.
%
% -------------------------------------------------------------------------
% CORE FEATURES
% -------------------------------------------------------------------------
%
% 1) MULTI-EXPERIMENT INPUT AND POOLING
%    - Accepts one or multiple GFP_Puncta_Summary.csv files.
%
%    - Each CSV is read independently using a robust Fiji-table reader.
%
%    - Valid tables are concatenated into one pooled analysis table.
%
%    - One Experiment label is assigned to every source CSV.
%
%    - Default experiment labels are:
%
%          Exp1
%          Exp2
%          Exp3
%          ...
%
%    - Custom labels can be supplied using:
%
%          opts.experimentLabels
%
%    - opts.experimentLabels must contain exactly one label per input CSV.
%
%    - The full source CSV path is retained in:
%
%          SourceCsv
%
% 2) ROBUST OLD/NEW FIJI SCHEMA HARMONISATION
%    - Both older and newer puncta-summary formats are converted to one
%      canonical MATLAB table structure.
%
%    - Canonical columns are:
%
%          File
%          Stage
%          Cell_Area
%          Cell_Mean_GFP
%          Cell_IntDen_GFP
%          Cell_SD_GFP
%          Threshold_SD
%          Threshold_Value
%          Min_Puncta_Size
%          NPuncta
%          Total_Puncta_Area
%          Mean_Puncta_Area
%          Largest_Punctum_Area
%          Mean_Puncta_Intensity
%          Total_Puncta_IntDen
%          Puncta_Fraction
%          Area_Fraction
%
%    - Header matching is case-insensitive.
%
%    - The reader searches for the first valid header row beginning with:
%
%          File,
%
%    - Empty lines are removed.
%
%    - Repeated header rows are skipped.
%
%    - Short rows are padded to the detected input schema.
%
%    - Trailing empty CSV columns are removed.
%
%    - Rows containing unexpected additional non-empty columns are skipped
%      with a warning rather than being incorrectly shifted into the
%      canonical schema.
%
%    - Missing numeric fields are represented as NaN.
%
% 3) BASIC TABLE CLEANUP
%    - File and Stage are converted to MATLAB string arrays.
%
%    - Rows with missing or empty File entries are removed.
%
%    - Accidental appended header rows containing:
%
%          File
%          Stage
%
%      are removed before analysis.
%
% 4) EXPERIMENTAL CONDITION PARSING
%    - Condition is inferred from the File entry.
%
%    - Filenames containing:
%
%          "veh"
%
%      are assigned:
%
%          Vehicle
%
%    - Filenames containing:
%
%          "h2o2"
%
%      are assigned:
%
%          H2O2
%
%    - Filenames containing neither recognised condition token are assigned:
%
%          Unknown
%
%    - Default condition order:
%
%          ["Vehicle","H2O2","Unknown"]
%
%    - Custom condition order can be supplied through:
%
%          opts.conditionOrder
%
% 5) TIMEPOINT PARSING
%    - Timepoints are inferred from the File entry using a general
%      minute-based regular expression.
%
%    - Recognised examples include:
%
%          5min
%          30min
%          30 min
%          30mins
%          60 mins
%          180min
%
%    - The parser extracts the numeric minute value and generates:
%
%          Timepoint
%          TimepointMinutes
%
%    - For example:
%
%          60min -> Timepoint = "60 min"
%                   TimepointMinutes = 60
%
%    - If no explicit minute-based timepoint is found, the file is assigned
%      opts.baselineTimepoint.
%
%    - Default:
%
%          opts.baselineTimepoint = "5 min"
%
%    - The numeric value of baselineTimepoint is extracted for
%      TimepointMinutes.
%
%    - This baseline fallback is intended for datasets in which baseline
%      filenames do not explicitly contain a timepoint token.
%
% 6) SEGMENTATION RUN TRACKING
%    - The function tracks segmentation settings so repeated Fiji analyses
%      of saved ROIs can be distinguished.
%
%    - Segmentation runs are defined using:
%
%          Threshold_SD
%          Min_Puncta_Size
%
%    - Threshold_Value is deliberately excluded from run identification
%      because it is a measured per-cell threshold and can vary between
%      individual cells/ROIs.
%
%    - When both segmentation settings are recorded, automatically generated
%      run labels have the form:
%
%          ThresholdSD_<value>**MinSize*<value>
%
%    - Decimal points and minus signs are converted to filename-safe text.
%
%    - Example:
%
%          Threshold_SD = 2.5
%          Min_Puncta_Size = 0.1
%
%      generates:
%
%          ThresholdSD_2p5__MinSize_0p1
%
%    - If neither segmentation setting is available, the default run label
%      is:
%
%          SingleRun_SettingsNotRecorded
%
% 7) MANUAL SEGMENTATION-SETTING OVERRIDES
%    - Older Fiji outputs do not record Threshold_SD or Min_Puncta_Size.
%
%    - These values can be supplied manually using:
%
%          opts.thresholdSDUsed
%          opts.minPunctaSizeUsed
%
%    - When a manual value is supplied, the corresponding canonical table
%      column is overwritten with that value for all pooled rows.
%
%    - A completely custom run label can be supplied using:
%
%          opts.runLabel
%
%    - When opts.runLabel is non-empty, that label is assigned to every row
%      and overrides automatic RunLabel construction.
%
% 8) STAGE AND TIMEPOINT FILTERING
%    - Selected stages can be excluded using:
%
%          opts.excludeStages
%
%    - Default:
%
%          opts.excludeStages = ["Stalled"]
%
%    - Selected timepoints can be excluded using:
%
%          opts.excludeTimepoints
%
%    - Default:
%
%          opts.excludeTimepoints = "30 min"
%
%    - Filtering occurs after filename metadata parsing and RunLabel
%      construction.
%
%    - The function stops with an error if no rows remain after filtering.
%
% 9) CATEGORY ORDERING
%    - Stage, Condition, Timepoint, and Experiment are converted to ordered
%      categorical variables before plotting and summarisation.
%
%    - Default stage order:
%
%          ["Horsetail","M1","M2","M2l","Spores"]
%
%    - Default condition order:
%
%          ["Vehicle","H2O2","Unknown"]
%
%    - Stage or condition values observed in the data but absent from the
%      preferred order are appended automatically.
%
%    - When opts.timeOrder is empty, timepoints are ordered numerically using
%      TimepointMinutes.
%
%    - A manual timepoint order can be supplied using:
%
%          opts.timeOrder
%
% 10) CLEANED TABLE AND RUN-SETTING EXPORT
%    - The complete cleaned, pooled analysis table is saved as:
%
%          GFP_Puncta_Cleaned.csv
%
%    - The cleaned table contains the harmonised Fiji measurements together
%      with:
%
%          Experiment
%          SourceCsv
%          Condition
%          Timepoint
%          TimepointMinutes
%          RunLabel
%
%    - A unique segmentation-run settings table is saved as:
%
%          GFP_Puncta_RunSettings.csv
%
%    - The run-settings table contains:
%
%          Experiment
%          RunLabel
%          Threshold_SD
%          Min_Puncta_Size
%          SourceCsv
%
% 11) PUNCTA METRICS
%    - The following metrics are analysed when present:
%
%          NPuncta
%              Number of puncta per cell.
%
%          Total_Puncta_Area
%              Total segmented puncta area per cell (um^2).
%
%          Mean_Puncta_Area
%              Mean segmented punctum area (um^2).
%
%          Largest_Punctum_Area
%              Area of the largest segmented punctum (um^2).
%
%          Mean_Puncta_Intensity
%              Mean fluorescence intensity of segmented puncta (a.u.).
%
%          Total_Puncta_IntDen
%              Total puncta integrated density (a.u. * um^2).
%
%          Puncta_Fraction
%              Fraction of total GFP signal assigned to puncta.
%
%          Area_Fraction
%              Fraction of total cell area occupied by segmented puncta.
%
%    - Metrics absent from the canonical analysis table are skipped with a
%      warning.
%
% 12) SEGMENTATION-RUN-SPECIFIC PLOTTING
%    - opts.plotEachRun controls whether distinct segmentation runs are
%      plotted separately.
%
%    - Default:
%
%          opts.plotEachRun = true
%
%    - When multiple RunLabel values are detected and plotEachRun=true:
%
%          each run is subset independently
%          each run receives a dedicated output folder
%          a run-specific cleaned table is saved
%          all available puncta metrics are plotted separately for that run
%
%    - Run-specific output folders use the structure:
%
%          Plots*<RunLabel>
%
%    - Run-specific cleaned tables are saved as:
%
%          GFP_Puncta_Cleaned_<RunLabel>.csv
%
%    - When only one RunLabel exists, plots are generated directly in
%      outDir.
%
%    - IMPORTANT:
%      If multiple RunLabel values exist but opts.plotEachRun=false, all
%      retained rows are displayed together in the same plots.
%
%      The descriptive summary CSV files remain stratified by RunLabel.
%
% 13) POOLED CELL/ROI DOT PLOTS
%    - One figure is generated for each available puncta metric.
%
%    - Data are organised by:
%
%          Stage × Timepoint × Condition
%
%    - Each displayed dot represents one individual cell/ROI measurement.
%
%    - Dots from different experiments are distinguished using different
%      shades of the treatment colour.
%
%    - Vehicle experiments use a dark-to-light purple gradient.
%
%    - H2O2 experiments use a dark-to-light grey gradient.
%
%    - Unknown conditions use a blue fallback gradient.
%
%    - Dots are horizontally jittered to improve visibility.
%
%    - Vehicle and H2O2 positions are grouped closely within each timepoint.
%
%    - Timepoint groups are separated within each stage block.
%
%    - Stage blocks are separated by light vertical lines.
%
%    - X-axis ticks are positioned at the centre of each condition pair and
%      labelled by timepoint.
%
%    - The currently active plotting code does not display separate stage
%      text labels underneath the stage blocks.
%
% 14) POOLED MEDIAN DISPLAY
%    - For every Stage × Timepoint × Condition subgroup, the function pools
%      all retained cell/ROI values contributing to the displayed table
%      subset.
%
%    - The subgroup median is calculated as:
%
%          median(all cell/ROI values)
%
%    - The pooled cell/ROI median is displayed as a black horizontal line.
%
%    - The black line is NOT an experiment-level median and is NOT the
%      median of experiment medians.
%
%    - When run-specific plotting is active, the pooled median is calculated
%      within the selected RunLabel subset.
%
%    - When multiple runs are plotted together with plotEachRun=false, the
%      pooled median can contain cell/ROI values from multiple segmentation
%      settings.
%
% 15) FIGURE FORMATTING
%    - Figures use an A4 landscape-friendly canvas:
%
%          29.7 cm × 21.0 cm
%
%    - The plotting area is manually positioned using ax.Position.
%
%    - Additional right-side space is reserved when the legend is enabled.
%
%    - Y-axis limits are calculated independently for each metric and plot
%      subset.
%
%    - Automatic y-axis limits use the finite plotted measurements with
%      approximately 10% range padding.
%
%    - The lower y-limit is prevented from falling below zero.
%
%    - Timepoint x-axis labels use:
%
%          30-point bold font
%
%    - Numeric y-axis labels use:
%
%          20-point normal font
%
%    - Y-axis titles use:
%
%          26-point bold font
%
%    - The top and right box edges are removed.
%
%    - The y-axis remains on the left.
%
%    - The x-axis remains at the bottom.
%
%    - X-axis tick marks are hidden while x-axis labels are retained.
%
%    - Figures have no title.
%
%    - The y-axis labels include area and intensity units where applicable.
%
% 16) OPTIONAL EXPERIMENT / CONDITION LEGEND
%    - Controlled with:
%
%          opts.includeLegend
%
%    - Default:
%
%          opts.includeLegend = true
%
%    - The legend contains one entry for every:
%
%          Condition × Experiment
%
%      colour/shade combination.
%
%    - A separate legend entry identifies the black pooled-median line.
%
%    - When the legend is disabled, the plotting area is expanded to use
%      more of the A4 page.
%
% 17) POOLED DESCRIPTIVE SUMMARY
%    - A descriptive summary pooled across experiments is generated using:
%
%          RunLabel
%          Timepoint
%          Condition
%          Stage
%
%      as grouping variables.
%
%    - For every available puncta metric, groupsummary calculates:
%
%          mean
%          median
%          standard deviation
%
%    - The resulting table is saved as:
%
%          GFP_Puncta_GroupSummary_Pooled.csv
%
%    - These values describe pooled cell/ROI measurements.
%
% 18) PER-EXPERIMENT DESCRIPTIVE SUMMARY
%    - A second descriptive summary retains experiment identity.
%
%    - Grouping variables are:
%
%          Experiment
%          RunLabel
%          Timepoint
%          Condition
%          Stage
%
%    - For every available puncta metric, groupsummary calculates:
%
%          mean
%          median
%          standard deviation
%
%    - The resulting table is saved as:
%
%          GFP_Puncta_GroupSummary_ByExperiment.csv
%
%    - This table can be used for downstream analyses in which the
%      experiment, rather than the individual cell/ROI, is the intended
%      biological unit of replication.
%
% -------------------------------------------------------------------------
% OUTPUT
% -------------------------------------------------------------------------
% This function does not return a MATLAB output variable.
%
% The following files can be generated in outDir:
%
%   - GFP_Puncta_Cleaned.csv
%       Complete cleaned and harmonised pooled analysis table.
%
%   - GFP_Puncta_RunSettings.csv
%       Unique experiment and segmentation-run setting combinations.
%
%   - GFP_Puncta_GroupSummary_Pooled.csv
%       Mean, median, and standard deviation of puncta metrics pooled across
%       cell/ROI measurements from all experiments, stratified by RunLabel,
%       Timepoint, Condition, and Stage.
%
%   - GFP_Puncta_GroupSummary_ByExperiment.csv
%       Mean, median, and standard deviation calculated separately for each
%       experiment, RunLabel, Timepoint, Condition, and Stage.
%
%   - <metric>*byStageCondition_PooledMedian<runSuffix>.png
%       300-dpi puncta metric figure.
%
%   - <metric>*byStageCondition_PooledMedian<runSuffix>.fig
%       Editable MATLAB figure.
%
% When multiple segmentation runs are separated:
%
%   - Plots*<RunLabel>
%       Dedicated output directory for each segmentation run.
%
%   - GFP_Puncta_Cleaned*<RunLabel>.csv
%       Cleaned table containing only the selected segmentation run.
%
% -------------------------------------------------------------------------
% DESIGN PRINCIPLES
% -------------------------------------------------------------------------
% - Supports both historical and current Fiji puncta-summary schemas through
%   one canonical MATLAB table.
%
% - Preserves experiment and source-file provenance after multi-experiment
%   pooling.
%
% - Distinguishes user-defined segmentation parameters from measured
%   per-cell threshold values.
%
% - Tracks segmentation settings explicitly so repeated segmentation runs
%   can be identified and compared.
%
% - Separates segmentation runs by default when multiple RunLabel values are
%   detected.
%
% - Retains individual cell/ROI distributions in the visualisations while
%   providing pooled descriptive medians.
%
% - Provides both pooled cell/ROI descriptive summaries and experiment-
%   stratified summaries for downstream analysis.
%
% - Does not interpret pooled cell/ROI medians as experiment-level
%   biological replicates.
%
% - Does not perform inferential statistical testing.
%
% -------------------------------------------------------------------------
% EXAMPLE USAGE: MULTIPLE NEW-FORMAT FIJI OUTPUTS
% -------------------------------------------------------------------------
%
% punctaCsvs = [
%     "V:\Experiment1\Puncta\GFP_Puncta_Summary.csv"
%     "V:\Experiment2\Puncta\GFP_Puncta_Summary.csv"
%     "V:\Experiment3\Puncta\GFP_Puncta_Summary.csv"
% ];
%
% outDir = "V:\PooledPunctaAnalysis";
%
% opts = struct();
%
% opts.experimentLabels = ["Exp1","Exp2","Exp3"];
%
% opts.baselineTimepoint = "5 min";
% opts.excludeStages = ["Stalled"];
% opts.excludeTimepoints = "30 min";
%
% opts.stageOrder = ["Horsetail","M1","M2","M2l","Spores"];
% opts.conditionOrder = ["Vehicle","H2O2","Unknown"];
% opts.timeOrder = ["5 min","60 min"];
%
% opts.plotEachRun = true;
% opts.includeLegend = false;
%
% AnalyseGFPpunctaSummary(punctaCsvs, outDir, opts);
%
% -------------------------------------------------------------------------
% EXAMPLE USAGE: OLD-FORMAT FIJI OUTPUT
% -------------------------------------------------------------------------
%
% punctaCsv = ...
%     "V:\Experiment1\Puncta\GFP_Puncta_Summary.csv";
%
% outDir = "V:\Experiment1\Puncta\MATLAB_Analysis";
%
% opts = struct();
%
% % Manually record Fiji segmentation settings that are absent from the old
% % GFP_Puncta_Summary.csv schema.
% opts.thresholdSDUsed = 2.5;
% opts.minPunctaSizeUsed = 0.10;
%
% opts.excludeTimepoints = "30 min";
% opts.plotEachRun = true;
% opts.includeLegend = true;
%
% AnalyseGFPpunctaSummary(punctaCsv, outDir, opts);
%
% -------------------------------------------------------------------------
% Author: Raful Navarro Espindola
% Project: Mitochondrial distribution and GFP puncta analysis during fission
%          yeast meiosis
% -------------------------------------------------------------------------


    if nargin < 1 || isempty(punctaCsvs)
        error("Please provide one or more GFP_Puncta_Summary.csv files.");
    end

    punctaCsvs = string(punctaCsvs);
    punctaCsvs = punctaCsvs(:);

    if nargin < 3 || isempty(opts)
        opts = struct();
    end

    % ------------------------------------------------------
    % Defaults
    % ------------------------------------------------------
    opts = setDefault(opts, 'baselineTimepoint', "5 min");
    opts = setDefault(opts, 'excludeStages', ["Stalled"]);
    opts = setDefault(opts, 'excludeTimepoints', "30 min");
    opts = setDefault(opts, 'stageOrder', ["Horsetail","M1","M2","M2l","Spores"]);
    opts = setDefault(opts, 'conditionOrder', ["Vehicle","H2O2","Unknown"]);
    opts = setDefault(opts, 'timeOrder', strings(0,1));
    opts = setDefault(opts, 'plotEachRun', true);
    opts = setDefault(opts, 'includeLegend', true);

    % These are optional manual labels for old Fiji output.
    opts = setDefault(opts, 'thresholdSDUsed', NaN);
    opts = setDefault(opts, 'minPunctaSizeUsed', NaN);
    opts = setDefault(opts, 'runLabel', "");

    % Experiment labels.
    % If you do not provide these, the script will use Exp1, Exp2, Exp3, etc.
    opts = setDefault(opts, 'experimentLabels', "Exp" + string((1:numel(punctaCsvs))'));

    opts.experimentLabels = string(opts.experimentLabels);
    opts.experimentLabels = opts.experimentLabels(:);

    if numel(opts.experimentLabels) ~= numel(punctaCsvs)
        error("opts.experimentLabels must have one label per CSV file.");
    end

    if nargin < 2 || isempty(outDir)
        outDir = fullfile(fileparts(punctaCsvs(1)), "MATLAB_Analysis_Pooled");
    end

    if ~exist(outDir, 'dir')
        mkdir(outDir);
    end

    % ------------------------------------------------------
    % Read and pool all Fiji tables
    % ------------------------------------------------------
    T = table();

    for e = 1:numel(punctaCsvs)

        thisCsv = punctaCsvs(e);
        thisExp = opts.experimentLabels(e);

        fprintf("\nReading experiment %s:\n%s\n", thisExp, thisCsv);

        Te = readFijiPunctaSummaryRobust(thisCsv);

        if isempty(Te) || height(Te) == 0
            warning("No valid rows were found in %s. Skipping.", thisCsv);
            continue;
        end

        Te.Experiment = repmat(thisExp, height(Te), 1);
        Te.SourceCsv  = repmat(thisCsv, height(Te), 1);

        T = [T; Te]; %#ok<AGROW>
    end

    if isempty(T) || height(T) == 0
        error("No valid rows were found in any of the supplied puncta summary CSV files.");
    end

    % ------------------------------------------------------
    % Basic cleanup
    % ------------------------------------------------------
    T.File  = string(T.File);
    T.Stage = string(T.Stage);

    % Remove empty rows
    T = T(~ismissing(T.File) & T.File ~= "", :);

    % Remove accidental repeated header rows, if the Fiji output was appended
    T = T(T.File ~= "File" & T.Stage ~= "Stage", :);

    % ------------------------------------------------------
    % Parse metadata from filename
    % ------------------------------------------------------
    T.Condition = strings(height(T),1);
    T.Timepoint = strings(height(T),1);
    T.TimepointMinutes = nan(height(T),1);

    for i = 1:height(T)

        fname = string(T.File(i));
        lowerName = lower(fname);

        % ---- Condition ----
        if contains(lowerName, "veh")
            T.Condition(i) = "Vehicle";
        elseif contains(lowerName, "h2o2")
            T.Condition(i) = "H2O2";
        else
            T.Condition(i) = "Unknown";
        end

        % ---- Timepoint ----
        % Looks for patterns such as:
        %   30min
        %   30 min
        %   30mins
        %   60 mins
        tok = regexp(char(fname), '(\d+)\s*mins?', 'tokens', 'once', 'ignorecase');

        if ~isempty(tok)
            mins = str2double(tok{1});
            T.TimepointMinutes(i) = mins;
            T.Timepoint(i) = string(mins) + " min";
        else
            T.Timepoint(i) = opts.baselineTimepoint;
            T.TimepointMinutes(i) = parseMinutesFromLabel(opts.baselineTimepoint);
        end
    end

    % ------------------------------------------------------
    % Build run labels from segmentation settings
    % ------------------------------------------------------
    % This is useful when the same saved ROIs are analysed multiple times
    % using different Fiji threshold settings.
    % ------------------------------------------------------
    % If the Fiji CSV is old-format, it does not contain the
    % actual segmentation settings. You can optionally provide
    % them through opts.thresholdSDUsed and opts.minPunctaSizeUsed.
    % ------------------------------------------------------
    if ismember("Threshold_SD", string(T.Properties.VariableNames)) && ...
            ~isnan(opts.thresholdSDUsed)

        T.Threshold_SD(:) = opts.thresholdSDUsed;
    end

    if ismember("Min_Puncta_Size", string(T.Properties.VariableNames)) && ...
            ~isnan(opts.minPunctaSizeUsed)

        T.Min_Puncta_Size(:) = opts.minPunctaSizeUsed;
    end

    T.RunLabel = buildRunLabels(T, opts);

    % ------------------------------------------------------
    % Filter unwanted stages/timepoints
    % ------------------------------------------------------
    if ~isempty(opts.excludeStages)
        T = T(~ismember(string(T.Stage), string(opts.excludeStages)), :);
    end

    if ~isempty(opts.excludeTimepoints)
        T = T(~ismember(string(T.Timepoint), string(opts.excludeTimepoints)), :);
    end

    if height(T) == 0
        error("No rows remain after filtering stages/timepoints.");
    end

    % ------------------------------------------------------
    % Standardise category order
    % ------------------------------------------------------
    stageOrder = completeOrder(opts.stageOrder, unique(string(T.Stage), 'stable'));
    condOrder  = completeOrder(opts.conditionOrder, unique(string(T.Condition), 'stable'));

    if isempty(opts.timeOrder)
        timeOrder = inferTimeOrder(T);
    else
        timeOrder = completeOrder(opts.timeOrder, unique(string(T.Timepoint), 'stable'));
    end

    expOrder = completeOrder(opts.experimentLabels, unique(string(T.Experiment), 'stable'));

    T.Stage      = categorical(T.Stage, stageOrder, 'Ordinal', true);
    T.Condition  = categorical(T.Condition, condOrder, 'Ordinal', true);
    T.Timepoint  = categorical(T.Timepoint, timeOrder, 'Ordinal', true);
    T.Experiment = categorical(T.Experiment, expOrder, 'Ordinal', true);

    % ------------------------------------------------------
    % Save cleaned table
    % ------------------------------------------------------
    writetable(T, fullfile(outDir, "GFP_Puncta_Cleaned.csv"));

    % Save run settings table
    runSettings = unique(T(:, ["Experiment","RunLabel","Threshold_SD","Min_Puncta_Size","SourceCsv"]), 'rows');
    writetable(runSettings, fullfile(outDir, "GFP_Puncta_RunSettings.csv"));

    % ------------------------------------------------------
    % Metrics to plot
    % ------------------------------------------------------
    metrics = {
        "NPuncta",               "Number of puncta per cell";
        "Total_Puncta_Area",     "Total puncta area (\mum^2)";
        "Mean_Puncta_Area",      "Mean puncta area (\mum^2)";
        "Largest_Punctum_Area",  "Largest punctum area (\mum^2)";
        "Mean_Puncta_Intensity", "Mean puncta intensity (a.u.)";
        "Total_Puncta_IntDen",   "Total puncta integrated density (a.u. \cdot \mum^2)";
        "Puncta_Fraction",       "Fraction of GFP signal in puncta";
        "Area_Fraction",         "Fraction of cell area occupied by puncta";
        };

    % ------------------------------------------------------
    % Plot
    % ------------------------------------------------------
    runLabels = unique(string(T.RunLabel), 'stable');

    if opts.plotEachRun && numel(runLabels) > 1

        fprintf("Multiple segmentation settings detected.\n");
        fprintf("Plots will be generated separately for each setting.\n\n");

        for r = 1:numel(runLabels)

            thisRun = runLabels(r);
            Tr = T(string(T.RunLabel) == thisRun, :);

            runOutDir = fullfile(outDir, "Plots_" + makeSafeFolderName(thisRun));

            if ~exist(runOutDir, 'dir')
                mkdir(runOutDir);
            end

            writetable(Tr, fullfile(runOutDir, "GFP_Puncta_Cleaned_" + makeSafeFolderName(thisRun) + ".csv"));

            for m = 1:size(metrics,1)
                metricName = metrics{m,1};
                yLabelText = metrics{m,2};

                if ismember(metricName, string(Tr.Properties.VariableNames))
                    makePunctaPlot(Tr, metricName, yLabelText, runOutDir, thisRun, opts.includeLegend);
                else
                    warning("Metric %s was not found in the table. Skipping.", metricName);
                end
            end
        end

    else

        for m = 1:size(metrics,1)
            metricName = metrics{m,1};
            yLabelText = metrics{m,2};

            if ismember(metricName, string(T.Properties.VariableNames))
                makePunctaPlot(T, metricName, yLabelText, outDir, "", opts.includeLegend);
            else
                warning("Metric %s was not found in the table. Skipping.", metricName);
            end
        end
    end

    % ------------------------------------------------------
    % Summary table
    % ------------------------------------------------------
    summaryMetrics = [
        "NPuncta"
        "Total_Puncta_Area"
        "Mean_Puncta_Area"
        "Largest_Punctum_Area"
        "Mean_Puncta_Intensity"
        "Total_Puncta_IntDen"
        "Puncta_Fraction"
        "Area_Fraction"
    ];

    summaryMetrics = summaryMetrics(ismember(summaryMetrics, string(T.Properties.VariableNames)));

    % Pooled summary across all experiments
    groupVarsPooled = ["RunLabel","Timepoint","Condition","Stage"];
    Gpooled = groupsummary(T, groupVarsPooled, ["mean","median","std"], summaryMetrics);
    writetable(Gpooled, fullfile(outDir, "GFP_Puncta_GroupSummary_Pooled.csv"));

    % Per-experiment summary
    groupVarsExp = ["Experiment","RunLabel","Timepoint","Condition","Stage"];
    Gexp = groupsummary(T, groupVarsExp, ["mean","median","std"], summaryMetrics);
    writetable(Gexp, fullfile(outDir, "GFP_Puncta_GroupSummary_ByExperiment.csv"));

    fprintf("Done. Outputs saved to:\n%s\n", outDir);
end


% ========================================================================
% PLOTTING FUNCTION
% ========================================================================
function makePunctaPlot(T, metricName, yLabelText, outDir, runLabel, includeLegend)

    stageCats = string(categories(T.Stage));
    timeCats  = string(categories(T.Timepoint));
    condCats  = string(categories(T.Condition));
    expCats   = string(categories(T.Experiment));

    nStage = numel(stageCats);
    nTime  = numel(timeCats);
    nCond  = numel(condCats);
    nExp   = numel(expCats);

    if nargin < 6 || isempty(includeLegend)
        includeLegend = true;
    end

    % --------------------------------------------------
    % Build all timepoint-condition combinations
    % Order will be:
    % 5 min Vehicle, 5 min H2O2, 60 min Vehicle, 60 min H2O2
    % provided that timeCats and condCats are ordered that way upstream.
    % --------------------------------------------------
    comboTimes  = strings(0,1);
    comboConds  = strings(0,1);
    comboLabels = strings(0,1);

    for t = 1:nTime
        for c = 1:nCond
            comboTimes(end+1,1) = timeCats(t); %#ok<AGROW>
            comboConds(end+1,1) = condCats(c); %#ok<AGROW>

            condLabel = condCats(c);

            if condLabel == "Vehicle"
                condLabel = "Vehicle";
            elseif condLabel == "H2O2"
                condLabel = "H_2O_2";
            end

            comboLabels(end+1,1) = timeCats(t) + newline + condLabel;
        end
    end

    nCombos = numel(comboTimes);

    % --------------------------------------------------
    % Layout settings
    % --------------------------------------------------
    dotSize = 180;
    jitterAmount = 0.25;
    medianHalfWidth = 0.18;
    stageGap = 1.4;

    % --------------------------------------------------
    % A4 landscape-friendly figure
    % --------------------------------------------------
    fig = figure('Color','w', ...
        'Units','centimeters', ...
        'Position', [2 2 29.7 21.0], ...
        'PaperUnits','centimeters', ...
        'PaperPosition', [0 0 29.7 21.0], ...
        'PaperSize', [29.7 21.0]);

    ax = axes(fig);
    hold(ax, 'on');

    if includeLegend
        % Leave room on the right for the legend
        ax.Position = [0.16 0.22 0.56 0.70];
    else
        % Use more of the page if no legend is shown
        ax.Position = [0.16 0.22 0.72 0.70];
    end

    % --------------------------------------------------
    % Shared y-axis limits
    % --------------------------------------------------
    yAll = T.(metricName);
    yAll = yAll(~isnan(yAll));

    if isempty(yAll)
        yLimits = [0 1];
    else
        yMin = min(yAll);
        yMax = max(yAll);

        if yMin == yMax
            yLimits = [0 yMax + 1];
        else
            padding = 0.10 * (yMax - yMin);
            yLimits = [max(0, yMin - padding), yMax + padding];
        end
    end

    yRange = yLimits(2) - yLimits(1);
    conditionLabelOffset = 0;   % increase this to move labels lower
    conditionLabelRoom   = 0;   % increase this if labels get cropped

    yText = yLimits(1) - conditionLabelOffset * yRange;

    % --------------------------------------------------
    % Compute x-positions for each stage group
    % with tighter Vehicle/H2O2 pairs within each timepoint
    % --------------------------------------------------

    stageCentres = zeros(nStage,1);
    allStagePositions = cell(nStage,1);

    conditionPairHalfWidth = 0.35;   % smaller = Vehicle/H2O2 closer together
    timeSpacing            = 1.6;   % distance between 5 min and 60 min groups
    stageGap               = 1.40;   % distance between stages

    if nCond == 1
        condOffsets = 0;
    else
        condOffsets = linspace(-conditionPairHalfWidth, conditionPairHalfWidth, nCond);
    end

    timeCentres = 1 + (0:nTime-1) * timeSpacing;

    stageWidth = max(timeCentres) - min(timeCentres) + 2 * conditionPairHalfWidth;

    for s = 1:nStage

        groupStart = (s-1) * (stageWidth + stageGap);

        xPos = nan(1, nCombos);

        for k = 1:nCombos

            thisTime = comboTimes(k);
            thisCond = comboConds(k);

            tIdx = find(timeCats == thisTime, 1, 'first');
            cIdx = find(condCats == thisCond, 1, 'first');

            xPos(k) = groupStart + timeCentres(tIdx) + condOffsets(cIdx);
        end

        allStagePositions{s} = xPos;
        stageCentres(s) = mean(groupStart + timeCentres);
    end

    % --------------------------------------------------
    % X-axis tick labels: one tick per timepoint,
    % centred between Vehicle and H2O2
    % --------------------------------------------------
    timeTickPositions = [];
    timeTickLabels = strings(0,1);

    for s = 1:nStage

        xPos = allStagePositions{s};

        for t = 1:nTime

            idxThisTime = find(comboTimes == timeCats(t));

            if isempty(idxThisTime)
                continue;
            end

            % For each stage, this gives the midpoint between
            % Vehicle and H2O2 for the current timepoint
            thisTimeX = mean(xPos(idxThisTime));

            timeTickPositions(end+1) = thisTimeX; %#ok<AGROW>
            timeTickLabels(end+1,1) = timeCats(t); %#ok<AGROW>
        end
    end

    % --------------------------------------------------
    % Plot dots and pooled median bars
    % --------------------------------------------------
    for s = 1:nStage

        stageName = stageCats(s);
        xPos = allStagePositions{s};

        for k = 1:nCombos

            thisTime = comboTimes(k);
            thisCond = comboConds(k);
            xCentre  = xPos(k);

            Tc = T( ...
                string(T.Stage) == stageName & ...
                string(T.Timepoint) == thisTime & ...
                string(T.Condition) == thisCond, :);

            if isempty(Tc)
                continue;
            end

            % ------------------------------
            % Individual cell values by experiment
            % ------------------------------
            for e = 1:nExp

                expName = expCats(e);
                Te = Tc(string(Tc.Experiment) == expName, :);

                if isempty(Te)
                    continue;
                end

                x = xCentre + jitterAmount * (rand(height(Te),1) - 0.5);
                thisColour = experimentConditionColour(thisCond, e, nExp);

                scatter(x, Te.(metricName), dotSize, ...
                    'MarkerFaceColor', thisColour, ...
                    'MarkerEdgeColor', 'k', ...
                    'LineWidth', 0.35, ...
                    'MarkerFaceAlpha', 0.65);
            end

            % ------------------------------
            % Pooled median as black horizontal bar
            % ------------------------------
            y = Tc.(metricName);
            y = y(~isnan(y));

            if ~isempty(y)
                yMed = median(y, 'omitnan');

                plot([xCentre - medianHalfWidth, xCentre + medianHalfWidth], ...
                     [yMed, yMed], ...
                     'k-', ...
                     'LineWidth', 2.4);
            end

            % ------------------------------
            % Subgroup labels under each position
            % ------------------------------
            %text(xCentre, yText, comboLabels(k), ...
            %    'HorizontalAlignment', 'center', ...
            %    'VerticalAlignment', 'top', ...
            %    'FontSize', 16, ...
            %    'FontWeight', 'bold', ...
            %    'Interpreter', 'tex', ...
            %    'Clipping', 'off');

            %stageLabelOffset = 0.1;   % increase to push Horsetail lower
            %stageLabelY = yLimits(1) - stageLabelOffset * yRange;

            %for s = 1:nStage
            %    text(stageCentres(s), stageLabelY, stageCats(s), ...
            %        'HorizontalAlignment', 'center', ...
            %        'VerticalAlignment', 'top', ...
            %        'FontSize', 30, ...
            %        'FontWeight', 'bold', ...
            %        'Clipping', 'off');
            %end
        end
    end

    % --------------------------------------------------
    % Light separators between stages
    % --------------------------------------------------
    for s = 1:(nStage-1)
        xSep = (allStagePositions{s}(end) + allStagePositions{s+1}(1)) / 2;
        xline(xSep, '-', 'Color', [0.82 0.82 0.82], 'LineWidth', 1.2);
    end

    % --------------------------------------------------
    % Axis formatting
    % --------------------------------------------------
    xMin = allStagePositions{1}(1) - 0.8;
    xMax = allStagePositions{end}(end) + 0.8;

    xlim([xMin, xMax]);
    ylim([yLimits(1) - conditionLabelRoom * yRange, yLimits(2)]);

    xticks(timeTickPositions);
    xticklabels(timeTickLabels);

    ax.XAxis.FontSize = 30;
    ax.XAxis.FontWeight = 'bold';

    yl = ylabel(yLabelText, 'Interpreter', 'tex');

    % Numeric y-axis tick labels
    ax.YAxis.FontSize = 20;
    ax.YAxis.FontWeight = 'normal';

    % Y-axis title, treated separately
    yl.FontSize = 26;
    yl.FontWeight = 'bold';

    ax.LineWidth = 1.5;

    % Remove top/right axis ticks and box edges
    box(ax, 'off');

    % Keep y-axis only on the left
    ax.YAxisLocation = 'left';

    % Keep x-axis position at the bottom
    ax.XAxisLocation = 'bottom';

    % Remove x-axis tick marks but keep x-axis labels
    ax.XAxis.TickLength = [0 0];

    % Optional: keep y-axis tick marks on the left
    ax.YAxis.TickLength = [0.01 0.01];

    % No figure title
    if strlength(runLabel) > 0
        fileSuffix = "_" + makeSafeFolderName(runLabel);
    else
        fileSuffix = "";
    end

    % Legend
    if includeLegend
        makeLegend(condCats, expCats);
    end

    exportgraphics(fig, fullfile(outDir, metricName + "_byStageCondition_PooledMedian" + fileSuffix + ".png"), ...
        'Resolution', 300);

    savefig(fig, fullfile(outDir, metricName + "_byStageCondition_PooledMedian" + fileSuffix + ".fig"));

    close(fig);
end

% ========================================================================
% ROBUST FIJI CSV READER
% ========================================================================
function T = readFijiPunctaSummaryRobust(punctaCsv)
% readFijiPunctaSummaryRobust
%
% Reads both old and new Fiji GFP_Puncta_Summary.csv files.
%
% Old Fiji format:
%   File,Stage,...,Threshold,NPuncta,...
%
% New Fiji format:
%   File,Stage,...,Threshold_SD,Threshold_Value,Min_Puncta_Size,NPuncta,...
%
% Important:
%   The old "Threshold" column is a measured per-cell threshold value,
%   not the user-defined threshold SD setting.

    canonicalCols = [
        "File"
        "Stage"
        "Cell_Area"
        "Cell_Mean_GFP"
        "Cell_IntDen_GFP"
        "Cell_SD_GFP"
        "Threshold_SD"
        "Threshold_Value"
        "Min_Puncta_Size"
        "NPuncta"
        "Total_Puncta_Area"
        "Mean_Puncta_Area"
        "Largest_Punctum_Area"
        "Mean_Puncta_Intensity"
        "Total_Puncta_IntDen"
        "Puncta_Fraction"
        "Area_Fraction"
    ]';

    lines = readlines(punctaCsv);
    lines = strip(lines);
    lines = lines(strlength(lines) > 0);

    if isempty(lines)
        T = table();
        return;
    end

    headerIdx = find(startsWith(lower(lines), "file,"), 1, 'first');

    if isempty(headerIdx)
        error("Could not find a valid header row starting with 'File,'.");
    end

    header = split(lines(headerIdx), ",");
    header = strip(header(:))';

    rows = strings(0, numel(canonicalCols));

    skippedRows = 0;

    for i = headerIdx+1:numel(lines)

        line = lines(i);

        parts = split(line, ",");
        parts = strip(parts(:))';

        % Remove trailing empty columns.
        % This prevents an old-format row with extra trailing commas from
        % being mistaken for a new-format row.
        while ~isempty(parts) && strlength(parts(end)) == 0
            parts(end) = [];
        end

        if isempty(parts)
            continue;
        end

        % Skip repeated header rows.
        if lower(parts(1)) == "file"
            continue;
        end

        % Pad short rows.
        if numel(parts) < numel(header)
            parts(end+1:numel(header)) = "";
        end

        % If there are extra non-empty columns, skip the row.
        if numel(parts) > numel(header)
            extraParts = parts(numel(header)+1:end);

            if all(strlength(strip(extraParts)) == 0)
                parts = parts(1:numel(header));
            else
                skippedRows = skippedRows + 1;
                warning("Skipping line %d because it has unexpected extra columns.", i);
                continue;
            end
        end

        row = strings(1, numel(canonicalCols));

        for c = 1:numel(canonicalCols)

            cname = canonicalCols(c);

            if cname == "Threshold_SD"

                % Only use Threshold_SD when the column genuinely exists.
                % Do NOT map old "Threshold" to Threshold_SD.
                if hasColumn(header, "Threshold_SD")
                    row(c) = getColumnValue(header, parts, "Threshold_SD");
                else
                    row(c) = "NaN";
                end

            elseif cname == "Threshold_Value"

                % New Fiji output uses Threshold_Value.
                % Old Fiji output uses Threshold.
                if hasColumn(header, "Threshold_Value")
                    row(c) = getColumnValue(header, parts, "Threshold_Value");
                elseif hasColumn(header, "Threshold")
                    row(c) = getColumnValue(header, parts, "Threshold");
                else
                    row(c) = "NaN";
                end

            elseif cname == "Min_Puncta_Size"

                % Only use Min_Puncta_Size when the column genuinely exists.
                if hasColumn(header, "Min_Puncta_Size")
                    row(c) = getColumnValue(header, parts, "Min_Puncta_Size");
                else
                    row(c) = "NaN";
                end

            else

                if hasColumn(header, cname)
                    row(c) = getColumnValue(header, parts, cname);
                else
                    if cname == "File" || cname == "Stage"
                        row(c) = "";
                    else
                        row(c) = "NaN";
                    end
                end
            end
        end

        rows(end+1, :) = row; %#ok<AGROW>
    end

    if isempty(rows)
        T = table();
        return;
    end

    T = array2table(rows, 'VariableNames', cellstr(canonicalCols));

    T.File = string(T.File);
    T.Stage = string(T.Stage);

    numericVars = canonicalCols(3:end);

    for v = 1:numel(numericVars)
        varName = numericVars(v);
        T.(varName) = str2double(string(T.(varName)));
    end

    fprintf("Read %d valid rows from:\n%s\n", height(T), punctaCsv);

    if skippedRows > 0
        fprintf("Skipped %d malformed rows.\n", skippedRows);
    end
end


% ========================================================================
% HELPER FUNCTIONS
% ========================================================================
function tf = hasColumn(header, columnName)

    tf = any(strcmpi(string(header), string(columnName)));
end


function value = getColumnValue(header, parts, columnName)

    idx = find(strcmpi(string(header), string(columnName)), 1, 'first');

    if isempty(idx) || idx > numel(parts)
        value = "";
    else
        value = parts(idx);
    end
end

function opts = setDefault(opts, fieldName, defaultValue)

    if ~isfield(opts, fieldName) || isempty(opts.(fieldName))
        opts.(fieldName) = defaultValue;
    end
end


function labels = buildRunLabels(T, opts)
% buildRunLabels
%
% Creates one run label per row.
%
% Important:
%   Threshold_Value is NOT used here because it is a measured per-cell
%   threshold and therefore changes from cell to cell.
%
%   Only Threshold_SD and Min_Puncta_Size should define segmentation runs.

    labels = strings(height(T), 1);

    if nargin < 2 || isempty(opts)
        opts = struct();
    end

    if isfield(opts, 'runLabel') && strlength(string(opts.runLabel)) > 0
        labels(:) = string(opts.runLabel);
        return;
    end

    hasThresholdSD = ismember("Threshold_SD", string(T.Properties.VariableNames));
    hasMinSize     = ismember("Min_Puncta_Size", string(T.Properties.VariableNames));

    for i = 1:height(T)

        parts = strings(0,1);

        if hasThresholdSD && ~isnan(T.Threshold_SD(i))
            parts(end+1) = "ThresholdSD_" + numberToLabel(T.Threshold_SD(i)); %#ok<AGROW>
        end

        if hasMinSize && ~isnan(T.Min_Puncta_Size(i))
            parts(end+1) = "MinSize_" + numberToLabel(T.Min_Puncta_Size(i)); %#ok<AGROW>
        end

        if isempty(parts)
            labels(i) = "SingleRun_SettingsNotRecorded";
        else
            labels(i) = strjoin(parts, "__");
        end
    end
end


function out = numberToLabel(x)

    out = string(sprintf('%g', x));
    out = replace(out, ".", "p");
    out = replace(out, "-", "minus");
end


function safeName = makeSafeFolderName(name)

    safeName = string(name);
    safeName = replace(safeName, " ", "_");
    safeName = replace(safeName, ".", "p");
    safeName = replace(safeName, "/", "_");
    safeName = replace(safeName, "\", "_");
    safeName = replace(safeName, ":", "_");
    safeName = replace(safeName, ";", "_");
    safeName = replace(safeName, ",", "_");
    safeName = replace(safeName, "|", "_");
end


function mins = parseMinutesFromLabel(label)

    tok = regexp(char(label), '(\d+)', 'tokens', 'once');

    if isempty(tok)
        mins = NaN;
    else
        mins = str2double(tok{1});
    end
end


function outOrder = completeOrder(preferredOrder, observedValues)

    preferredOrder = string(preferredOrder);
    observedValues = string(observedValues);

    outOrder = preferredOrder(ismember(preferredOrder, observedValues));

    extras = observedValues(~ismember(observedValues, outOrder));

    outOrder = [outOrder(:); extras(:)];
end


function timeOrder = inferTimeOrder(T)

    observedTimes = unique(string(T.Timepoint), 'stable');

    mins = nan(numel(observedTimes),1);

    for i = 1:numel(observedTimes)
        idx = find(string(T.Timepoint) == observedTimes(i), 1, 'first');
        mins(i) = T.TimepointMinutes(idx);
    end

    [~, orderIdx] = sort(mins);

    timeOrder = observedTimes(orderIdx);
end


function colour = experimentConditionColour(condName, expIdx, nExp)

    condName = string(condName);

    if nExp <= 1
        shadeFactor = 0.35;
    else
        shadeFactor = (expIdx - 1) / (nExp - 1);
    end

    if condName == "Vehicle"

        % Purple shades: dark to light
        darkColour  = [0.28 0.00 0.45];
        lightColour = [0.78 0.62 0.90];

    elseif condName == "H2O2"

        % Grey shades: dark to light
        darkColour  = [0.20 0.20 0.20];
        lightColour = [0.75 0.75 0.75];

    else

        % Fallback for unknown conditions
        darkColour  = [0.10 0.10 0.60];
        lightColour = [0.60 0.60 0.95];
    end

    colour = darkColour .* (1 - shadeFactor) + lightColour .* shadeFactor;
end


function makeLegend(condCats, expCats)

    hold on;

    nCond = numel(condCats);
    nExp  = numel(expCats);

    h = gobjects(nCond * nExp + 1, 1);
    labels = strings(nCond * nExp + 1, 1);

    k = 0;

    for c = 1:nCond
        for e = 1:nExp

            k = k + 1;

            thisColour = experimentConditionColour(condCats{c}, e, nExp);

            h(k) = scatter(nan, nan, 180, ...
                'MarkerFaceColor', thisColour, ...
                'MarkerEdgeColor', 'k', ...
                'LineWidth', 0.35, ...
                'MarkerFaceAlpha', 0.65);

            labels(k) = string(condCats{c}) + " | " + string(expCats{e});
        end
    end

    h(end) = plot(nan, nan, 'k-', ...
        'LineWidth', 2.4);

    labels(end) = "Pooled median";

    legend(h, labels, 'Location', 'northeastoutside', 'Interpreter', 'none');
end